# Generated by Django 4.1.5 on 2023-01-17 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_plataforma', models.CharField(help_text='Ex.: AirBNB', max_length=100, verbose_name='Nome da plataforma de anúncio')),
                ('taxa_plataforma', models.CharField(help_text='Ex.: R$100,00', max_length=30, verbose_name='Taxa da Plataforma de anúncio')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_hospedes', models.CharField(help_text='Ex.: Máximo 05 hóspedes', max_length=25, verbose_name='Limite de Hóspedes')),
                ('qtd_banheiros', models.CharField(help_text='Ex.: 02 Banheiros', max_length=25, verbose_name='Quantidade de Banheiros')),
                ('aceita_animal', models.BooleanField(default=True)),
                ('valor_limpeza', models.CharField(help_text='Ex.: R$250,00', max_length=25, verbose_name='Valor da Limpeza')),
                ('data_ativacao', models.DateField(verbose_name='Data da ativação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_checkin', models.DateTimeField(help_text='Momento em que inicia o checkIN', verbose_name='Check-in inicia em')),
                ('data_checkout', models.DateTimeField(help_text='Momento em que ocorre o checkOUT', verbose_name='Check-out ocorre em')),
                ('preco_total', models.CharField(help_text='Ex.: R$1.000,00', max_length=100, verbose_name='Valor total da reserva')),
                ('comentario', models.TextField(help_text='Incluir comentários sobre a reserva', max_length=400, verbose_name='Comentário da reserva')),
                ('numero_hospedes', models.BigIntegerField(help_text='Ex.: 5', verbose_name='Quantidade de hóspede da reserva')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desafio.anuncio')),
            ],
        ),
        migrations.AddField(
            model_name='anuncio',
            name='imovel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desafio.imovel'),
        ),
    ]
